services:
  fhir:
    build:
      context: ./fhir
      dockerfile: Dockerfile
    command: npm run start
    env_file:
      - ./fhir/.env
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db # Persist MongoDB data
    restart: always

volumes:
  mongo-data:
